

services:
  device-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5156:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DatabaseConnection=Host=postgres;Port=5432;Database=devices;Username=postgres;Password=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - device-network
    volumes:
      - ./backups:/app/Backups

  device-ui:
    build:
      context:  ../../SPA/DeviceMonitoringService/SPA/device-monitoring-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - device-api
    networks:
      - device-network

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - device-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  device-network:
    driver: bridge

volumes:
  postgres_data: