version: '3.8'

services:

  shopweb.api:
    image: device-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5156:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      db:
        condition: service_healthy
    networks:
      - devicenetwork

  devicemonitoringui:
    build:
      context: C:/Users/User/source/repos/DeviceMonitoringService/SPA/device-monitoring-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - shopweb.api
    networks:
      - devicenetwork

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - devicenetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  devicenetwork:
    driver: bridge

volumes:
  postgres_data: